create table if not exists public.article_time_verifications (
  id bigint generated by default as identity primary key,
  article_id text not null references public.articles(id) on delete cascade,
  claimed_published_at timestamptz,
  verified_published_at timestamptz,
  available_at timestamptz,
  verification_status text not null
    check (verification_status in ('verified', 'conflict', 'unverifiable')),
  verification_method text not null,
  evidence jsonb not null default '[]'::jsonb,
  verifier_version text not null,
  checked_at timestamptz not null default now(),
  unique (article_id, verifier_version)
);

create index if not exists article_time_verifications_status_idx
  on public.article_time_verifications (verification_status, checked_at desc);

create index if not exists article_time_verifications_article_idx
  on public.article_time_verifications (article_id, checked_at desc);

alter table public.article_time_verifications enable row level security;

comment on table public.article_time_verifications is
  'Append-only evidence for historical article publication and research-availability timestamps.';
