alter table public.signal_watchlists
  add column if not exists mapping_version text,
  add column if not exists mapping_sources jsonb not null default '[]'::jsonb;

comment on column public.signal_watchlists.mapping_version is
  'Version of the beneficiary research mapping used when the row was created.';
comment on column public.signal_watchlists.mapping_sources is
  'Official or primary-source URLs used to verify the company-level operating link.';

create table if not exists public.signal_beneficiary_mapping_snapshots (
  id bigint generated by default as identity primary key,
  signal_event_id text not null references public.signal_events(id) on delete cascade,
  symbol text not null,
  market text not null,
  company_name text not null,
  mapping_version text not null,
  value_chain_role text not null,
  causal_reason text not null,
  tracking_metrics jsonb not null default '[]'::jsonb,
  invalidation_conditions jsonb not null default '[]'::jsonb,
  mapping_sources jsonb not null default '[]'::jsonb,
  direct_operating_link boolean not null default false,
  as_of_date date not null,
  created_at timestamptz not null default now(),
  unique (signal_event_id, symbol, market, mapping_version)
);

create index if not exists signal_beneficiary_mapping_lookup_idx
  on public.signal_beneficiary_mapping_snapshots (signal_event_id, mapping_version, symbol);

alter table public.signal_beneficiary_mapping_snapshots enable row level security;

comment on table public.signal_beneficiary_mapping_snapshots is
  'Append-only, versioned company-level beneficiary research mappings.';
