create table if not exists public.signal_research_snapshots (
  id bigint generated by default as identity primary key,
  signal_event_id text not null references public.signal_events(id) on delete cascade,
  as_of_date date not null,
  snapshot_version text not null,
  heat_score numeric not null,
  heat_state text not null,
  confidence_score numeric not null,
  confidence_model_version text not null,
  validation_status text not null check (validation_status in ('pending', 'completed')),
  outcome_status text,
  supporting_evidence jsonb not null default '[]'::jsonb,
  counter_evidence jsonb not null default '[]'::jsonb,
  validation_conditions jsonb not null default '[]'::jsonb,
  invalidation_conditions jsonb not null default '[]'::jsonb,
  data_gaps jsonb not null default '[]'::jsonb,
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  unique (signal_event_id, snapshot_version)
);

create index if not exists signal_research_snapshots_as_of_idx
  on public.signal_research_snapshots (as_of_date desc, signal_event_id);

alter table public.signal_research_snapshots enable row level security;

comment on table public.signal_research_snapshots is
  'Append-only research contract separating heat, confidence, validation, outcome, supporting evidence, and counter evidence.';
