create table if not exists public.signal_lifecycle_snapshots (
  id bigint generated by default as identity primary key,
  continuity_key text not null,
  signal_event_id text references public.signal_events(id) on delete set null,
  as_of_date date not null,
  last_seen_as_of date not null,
  lifecycle_state text not null check (
    lifecycle_state in ('emerging', 'rising', 'sustained', 'cooling', 'reactivated', 'expired')
  ),
  previous_state text check (
    previous_state is null or
    previous_state in ('emerging', 'rising', 'sustained', 'cooling', 'reactivated', 'expired')
  ),
  transition_reason text not null,
  model_version text not null,
  created_at timestamptz not null default now(),
  unique (continuity_key, as_of_date, model_version)
);

create index if not exists signal_lifecycle_snapshots_lookup_idx
  on public.signal_lifecycle_snapshots (continuity_key, as_of_date desc);

alter table public.signal_lifecycle_snapshots enable row level security;

comment on table public.signal_lifecycle_snapshots is
  'Append-only monthly lifecycle observations. Historical signal rows are never rewritten.';
